In [ ]:
import numpy as np
import pandas as pd
import datetime

In [ ]:
R = np.matrix(np.zeros([2, 2]))
Q = np.matrix(np.zeros([2, 2]))

In [ ]:
def RMatrix(m, n):
  index=0;
  if(m>1):
   R[index, 1] = (m)*100
  if(m==1):
   R[index, 0] = -2
   index=1
  if(n==1):
    R[index, 1] = +100
  if(n==0):
    R[index, 1] = -1
  
  return R



In [ ]:
action = [0, 1]
gamma = 1
initial_state=0;

In [ ]:
df = pd.read_csv('/content/selfish-miner.csv')

In [ ]:
prev=df.loc[0,'Hash']
date_time_str=df.loc[0,'Timestamp']
date_time_obj =pd.to_datetime(date_time_str)
prevt=datetime.datetime.timestamp(date_time_obj)
start=1;
t=0
while(start<82):
  t=0
  count=1;
  if(df.loc[start,'Parent Hash']!=prev):
    count=1;
    start+1;
    if(prevt>= datetime.datetime.timestamp(pd.to_datetime(df.loc[start,'Timestamp']))):
      t=1;
    while((df.loc[start,'Hash']==prev) and (start<82)):
      count+1
      prev=df.loc[start,'Hash']
      start = start+1
    R1 = RMatrix(count, t)
    
    i=0;
    
    Q[i, action[0]] +=  R1[i, action[0]] + gamma * max(Q[i+1, action[0]], Q[i+1, action[1]])
    Q[i, action[1]] +=  R1[i, action[1]] + gamma * max(Q[i+1, action[0]], Q[i+1, action[1]])

    i = i + 1
    Q[i, action[0]] +=  R1[i, action[0]] + gamma * max(Q[0, action[0]], Q[initial_state, action[1]])
    Q[i, action[1]] +=  R1[i, action[1]] + gamma * max(Q[0, action[0]], Q[initial_state, action[1]])
  else:
    # if(prevt>= datetime.datetime.timestamp(pd.to_datetime(df.loc[start,'Timestamp']))):
    #   t=1;
    R1 = RMatrix(1, t)
   
    i=0;
    
    Q[i, action[0]] +=  R[i, action[0]] + gamma * max(Q[i+1, action[0]], Q[i+1, action[1]])
    Q[i, action[1]] +=  R1[i, action[1]] + gamma * max(Q[i+1, action[0]], Q[i+1, action[1]])

    i = i + 1
    Q[i, action[0]] +=  R1[i, action[0]] + gamma * max(Q[0, action[0]], Q[initial_state, action[1]])
    Q[i, action[1]] +=  R1[i, action[1]] + gamma * max(Q[0, action[0]], Q[initial_state, action[1]])
    
    
  prev=df.loc[start,'Hash'] 
  date_time_str=df.loc[start,'Timestamp']
  date_time_obj =pd.to_datetime(date_time_str)
  prevt=datetime.datetime.timestamp(date_time_obj) 
  start = start+1
  print (Q, "\n")

 
  
    
     

[[-2.  0.]
 [ 0. -1.]] 

[[-4.  0.]
 [ 0. -2.]] 

[[-6.  0.]
 [ 0. -3.]] 

[[-8.  0.]
 [ 0. -4.]] 

[[-10.   0.]
 [  0.  -5.]] 

[[-12.   0.]
 [  0.  -6.]] 

[[-14.   0.]
 [  0.  -7.]] 

[[-16.   0.]
 [  0.  -8.]] 

[[-18.   0.]
 [  0.  -9.]] 

[[-20.   0.]
 [  0. -10.]] 

[[-22.   0.]
 [  0. -11.]] 

[[-24.   0.]
 [  0. -12.]] 

[[-26.   0.]
 [  0. -13.]] 

[[-28.   0.]
 [  0. -14.]] 

[[-30.   0.]
 [  0. -15.]] 

[[-32.   0.]
 [  0. -16.]] 

[[-34.   0.]
 [  0. -17.]] 

[[-36.   0.]
 [  0. -18.]] 

[[-38.   0.]
 [  0. -19.]] 

[[-40.   0.]
 [  0. -20.]] 

[[-42.   0.]
 [  0. -21.]] 

[[-44.   0.]
 [  0. -22.]] 

[[-46.   0.]
 [  0. -23.]] 

[[-48.   0.]
 [  0. -24.]] 

[[-50.   0.]
 [  0. -25.]] 

[[-52.   0.]
 [  0. -26.]] 

[[-54.   0.]
 [  0. -27.]] 

[[-56.   0.]
 [  0. -28.]] 

[[-58.   0.]
 [  0. -29.]] 

[[-60.   0.]
 [  0. -30.]] 

[[-62.   0.]
 [  0. -31.]] 

[[-64.   0.]
 [  0. -32.]] 

[[-66.   0.]
 [  0. -33.]] 

[[-68.   0.]
 [  0. -34.]] 

[[-70.   0.]
 [  0. -35.]] 

[